apps/responses/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^(?P<profile_id>\d+)/menu/$', views.Menu.as_view(), name='menu'),
    url(r'^(?P<profile_id>\d+)/start-exercise/$',
        views.StartExercise.as_view(), name='start-exercise'),
    url(r'^(?P<response_session_id>\d+)/summary/$',
        views.ResponseSessionSummary.as_view(), name='summary'),

    url(r'^(?P<response_session_id>\d+)/save-response/$',
        views.SaveResponse.as_view(), name='save-response'),

    url(r'^(?P<profile_id>\d+)/responses-list/$',
        views.ResponsesSession.as_view(), name='responses-list'),

]

urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='profiles:profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^profiles/', include('apps.profiles.urls', namespace="profiles")),
    url(r'^responses/', include('apps.responses.urls', namespace="responses")),
    url(r'^verbs/', include('apps.verbs.urls', namespace="verbs")),
]

apps/responses/models.py
from django.db import models
from django.db.models.functions import Coalesce


class ResponseSession(models.Model):
    profile = models.ForeignKey(
        'profiles.Profile'
    )
    date = models.DateTimeField(
        auto_now_add=True
    )

    # TODO :move this to manager
    def get_results(self):
        results = self.verbs.aggregate(
            simple_past_correct=Coalesce(models.Sum(
                models.Case(
                    models.When(simple_past_correct=True, then=1),
                    output_field=models.IntegerField()
                )
            ), models.Value(0)),
            past_participle_correct=Coalesce(models.Sum(
                models.Case(
                    models.When(past_participle_correct=True, then=1),
                    output_field=models.IntegerField()
                )
            ), models.Value(0)),
            all=models.Count('pk')
        )
        results['summary'] = results['simple_past_correct'] + results['past_participle_correct']
        results['all2'] = results['all'] * 2
        return results

    def __unicode__(self):
        return u'{} {}'.format(self.profile, self.date)


class VerbResponse(models.Model):
    session = models.ForeignKey(
        ResponseSession,
        related_name='verbs'
    )
    verb = models.ForeignKey(
        'verbs.Verb'
    )
    simple_past = models.CharField(
        max_length=32
    )
    simple_past_correct = models.BooleanField(
    )
    past_participle = models.CharField(
        max_length=32
    )
    past_participle_correct = models.BooleanField(
    )

apps/responses/views.py
import json
from django.views.generic import TemplateView, View
from django.views.generic.base import TemplateResponseMixin
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

from apps.profiles import models as profiles_models
from apps.verbs import models as verbs_models
import models


class Menu(TemplateView):
    template_name = "responses/menu.html"

    def get_context_data(self, **kwargs):
        context = super(Menu, self).get_context_data(**kwargs)
        profile_id = kwargs.get('profile_id', 0)
        context['profile'] = get_object_or_404(profiles_models.Profile, pk=profile_id)
        return context


class StartExercise(TemplateResponseMixin, View):
    template_name = "responses/start_exercise.html"

    def get_profile(self, kwargs):
        profile_id = kwargs.get('profile_id', 0)
        profile = get_object_or_404(profiles_models.Profile, pk=profile_id)
        return profile

    def create_Response_session(self, profile):
        session = models.ResponseSession()
        session.profile = profile
        session.save()
        return session

    def get(self, request, *args, **kwargs):
        profile = self.get_profile(kwargs)
        response_session = self.create_Response_session(profile)
        context = {}
        context['profile'] = profile
        context['response_session'] = response_session
        return self.render_to_response(context)


class SaveResponse(View):

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(SaveResponse, self).dispatch(request, *args, **kwargs)

    def get_data_from_request(self, request):
        request_data = json.loads(request.body)
        data = {}
        data['response_session_id'] = request_data.get('response_session_id', 0)
        for attr in ['infinitive', 'simple_past', 'simple_past_correct',
                     'past_participle', 'past_participle_correct']:
            data[attr] = request_data.get(attr, '')
        return data

    def save_response(self, session, verb, response_data):
        response = models.VerbResponse()
        response.session = session
        response.verb = verb
        for attr in ['simple_past', 'simple_past_correct',
                     'past_participle', 'past_participle_correct']:
            setattr(response, attr, response_data[attr])
        response.save()

    def post(self, request, response_session_id):
        response_data = self.get_data_from_request(request)
        response_session = get_object_or_404(
            models.ResponseSession,
            pk=response_session_id
        )
        verb = get_object_or_404(
            verbs_models.Verb,
            infinitive=response_data['infinitive']
        )
        self.save_response(response_session, verb, response_data)
        return JsonResponse({})


class ResponsesSession(TemplateView):
    template_name = "responses/responses_sessions_list.html"

    def _format_result(self, result, all_):
        if all_ > 0:
            percent = round((float(result) / (all_)) * 100, 2)
        else:
            percent = 0
        return (percent, result, all_)

    def get_responses_json(self, profile):
        responses_sessions = models.ResponseSession.objects.filter(
            profile=profile
        ).order_by('-date')
        respones = []
        for session in responses_sessions:
            response = {'date': session.date.strftime('%d-%m-%Y %H:%I')}
            results = session.get_results()
            response['simple_past'] = self._format_result(
                results['past_participle_correct'], results['all']
            )
            response['past_participle'] = self._format_result(
                results['past_participle_correct'], results['all']
            )
            response['summary'] = self._format_result(
                results['summary'], results['all2']
            )
            respones.append(response)
        return json.dumps(respones)

    def get_context_data(self, **kwargs):
        context = super(ResponsesSession, self).get_context_data(**kwargs)
        profile_id = kwargs.get('profile_id', 0)
        profile = get_object_or_404(profiles_models.Profile, pk=profile_id)
        context['responses'] = self.get_responses_json(profile)
        context['profile'] = profile
        return context


class ResponseSessionSummary(TemplateView):
    template_name = "responses/summary.html"

    def get_context_data(self, **kwargs):
        context = super(ResponseSessionSummary, self).get_context_data(**kwargs)
        response_session_id = kwargs.get('response_session_id', 0)
        response_session = get_object_or_404(models.ResponseSession, pk=response_session_id)
        context['response_session'] = response_session
        context['results'] = response_session.get_results()
        return context

templates/responses/menu.html
{% extends 'base.html' %}

{% block profile %} - {{ profile }} {% endblock %}

{% block body %}
<div>
    <a href="{% url 'responses:start-exercise' profile.id %}" class="btn-xxl btn btn-primary btn-block btn-lg ">
        <h2>Start exercise</h2>
    </a>
    <a href="{% url 'responses:responses-list' profile.id %}" class="btn-xxl btn btn-primary btn-block btn-lg ">
        <h2>Browse results</h2>
    </a>
</div>
{% endblock %}

templates/responses/responses_sessions_list.html
{% extends 'base.html' %}

{% block profile %} - {{ profile }} {% endblock %}

{% block body %}
<div style="padding-bottom:30px;">
    <a href="{% url 'responses:menu' profile.id %}" class="btn-xxl btn btn-primary btn-block btn-lg ">
        <h2>Back to exercises</h2>
    </a>
</div>

<div ng-app="grammartinker">
    <div ng-controller="resultsController as vm" >
        <table ng-table="vm.tableParams" class="table table-condensed table-bordered table-striped">
          <tr ng-repeat="row in $data">
            <td data-title="'Date'"  sortable="'date'">{$ row.date $}</td>
            <td data-title="'Simple past'">
                <div class="progress-bar" role="progressbar" style="width: {$ row.simple_past[0] $}%">
                    {$ row.simple_past[0] $}%
                </div>
                <span class="pull-right">
                    {$ row.simple_past[1] $} / {$ row.simple_past[2] $}
                </span>
            </td>
            <td data-title="'Past participle'" >
                    <div class="progress-bar" role="progressbar" style="width: {$ row.past_participle[0] $}%">
                        {$ row.past_participle[0] $} %
                    </div>
                <span class="pull-right" >
                    {$ row.past_participle[1] $}/{$ row.past_participle[2] $}
                </span>
            </td>
          </tr>
        </table>
    </div>
</div>


{# move this to js file #}
{% endblock %}

{% block extra_js %}
    <script>{% include 'js/responses_table.js' %}</script>
{% endblock %}

templates/responses/start_exercise.html
{% extends 'base.html' %}
{% load static %}

{% block profile %} - {{ profile }} {% endblock %}

{% block body %}

<div ng-app="grammartinker">
    <div ng-controller="Exercise as vm" >
        <div ng-show="vm.loading" >
            <h1>Loading verbs...</h1>
            <div class='uil-ring-css' style='transform:scale(0.6);'>
                <div></div>
            </div>
        </div>

        <div ng-show="!vm.loading">
            <div class="row" >
                <h2 class="col-sm-6" >{$ vm.verb.infinitive $}</h2>
                <h2 class="col-sm-3 text-info" >
                    <strong>{$ vm.currentVerbIndex + 1 $}/{$ vm.verbsAmount $}</strong>
                </h2>
            </div>

            <form class="form-horizontal row col-sm-12" autocomplete="off">
                <div class="form-group" ng-class="{'has-feedback': vm.answered}" >
                    <label for="simple_past" class="col-sm-2 control-label">Simple past</label>
                    <div class="col-sm-3" ng-class="{'has-error': vm.answered && !vm.reponse.simple_past_correct, 'has-success': vm.answered && vm.reponse.simple_past_correct}" >
                        <input tabindex="1" ng-model="vm.reponse.simple_past" ng-readonly="vm.answered"  class="form-control" id="simple_past" />
                        <response answered="vm.answered" is-correct="vm.reponse.simple_past_correct" correct-response="vm.verb.simple_past"></response>
                    </div>
                </div>

                <div class="form-group" ng-class="{'has-feedback': vm.answered}" >
                    <label for="past_participle" class="col-sm-2 control-label">Past participle</label>
                    <div class="col-sm-3" ng-class="{'has-error': vm.answered && !vm.reponse.past_participle_correct, 'has-success': vm.answered && vm.reponse.past_participle_correct}" >
                        <input tabindex="2" ng-model="vm.reponse.past_participle" ng-readonly="vm.answered" id="past_participle" class="form-control" />
                        <response answered="vm.answered" is-correct="vm.reponse.past_participle_correct" correct-response="vm.verb.past_participle"></response>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-4">
                        <button tabindex="3" ng-click="vm.checkClick()" ng-show="!vm.answered" class="btn btn-primary" >Check answer</button>
                        <button tabindex="4" ng-click="vm.nextVerbClick()" ng-show="vm.answered && vm.verbsAmount-1 > vm.currentVerbIndex" class="btn btn-primary" >Next verb</button>
                    </div>
                    <div class="col-sm-4">
                        <a class="btn btn-warning" href="{% url 'responses:summary' response_session.id %}" >
                             Finish
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
    <script>{% include 'js/verbs.js' %}</script>
{% endblock %}

templates/responses/summary.html
{% extends 'base.html' %}

{% block profile %} - {{ response_session.profile }} {% endblock %}

{% block body %}
<div>
    <h1>{{ response_session.date  }}</h1>

    <h2>
        Simple past: {% widthratio results.simple_past_correct results.all 100 %}%
        {{ results.simple_past_correct }}/{{ results.all }}
    </h2>
    <h2>
        Past participle: {% widthratio results.past_participle_correct results.all 100 %}%
        {{ results.past_participle_correct }}/{{ results.all }}
    </h2>
    <h2>
        Summary: {% widthratio results.summary results.all2 100 %}%
        {{ results.summary }}/{{ results.all2 }}
    </h2>
    <a href="{% url 'responses:menu' response_session.profile.id %}" class="btn-xxl btn btn-primary btn-block btn-lg ">
        <h2>Back to exercises</h2>
    </a>
    <a href="{% url 'responses:start-exercise' response_session.profile.id %}" class="btn-xxl btn btn-primary btn-block btn-lg ">
        <h2>Start again</h2>
    </a>
</div>
{% endblock %}